Help compiler to convert from llvm::cl::opt to its std::string value
Fixes the error below when compiling with C++17:

lib/Transforms/IPO/PassManagerBuilder.cpp:175:19:
 error: call to deleted constructor of 'llvm::cl::opt<std::string>'
    PGOInstrGen = PGOOutputFile;
                  ^~~~~~~~~~~~~
include/llvm/Support/CommandLine.h:1325:3:
 note: 'opt' has been explicitly marked deleted here
  opt(const opt &) = delete;